In [1]:
import os
import pandas as pd
import yaml
import pickle

In [2]:
#Retreive local data path
with open('../config/paths.yaml','r') as file:
    paths_list = yaml.safe_load(file)
    PATH = os.path.abspath(paths_list['PATH'])

In [3]:
# Getting back the objects:
with open('../config/lists_radio.pkl', 'rb') as f:
    id_cols_radio,var_cols_radio,time_points,delta_time = pickle.load(f)

# Open cleaned data
data_radio = pd.read_csv(os.path.join(PATH,'tables','data_radio.csv'))
data_radio = data_radio.loc[data_radio.StudyDay.isin(['pre','2','4','6','8'])]
data_radio.head()

,Subject,StudyDay,10Percentile-firstorder,90Percentile-firstorder,Autocorrelation-glcm,Busyness-ngtdm,Class,ClusterProminence-glcm,ClusterShade-glcm,ClusterTendency-glcm,...,SumSquares-glcm,SurfaceArea-shape,SurfaceVolumeRatio-shape,TotalEnergy-firstorder,Uniformity-firstorder,Variance-firstorder,VoxelVolume-shape,ZoneEntropy-glszm,ZonePercentage-glszm,ZoneVariance-glszm
1,B03757,2,-898.0,-532.0,137.536546,235.133257,Infected,212997.51820,4287.083661,147.411096,...,39.705596,37015.24347,0.221905,1.503261e+10,0.096901,27707.43096,166787.9929,6.784057,0.120439,9.577950e+05
3,B03757,4,-914.0,-495.0,144.675238,343.480410,Infected,384872.23440,7262.845777,207.218931,...,54.686086,37199.49256,0.207574,1.692301e+10,0.109012,36959.53816,179172.8874,6.857994,0.117850,1.357291e+06
5,B03757,6,-910.0,-498.0,143.741245,343.089081,Infected,370488.96500,7079.166770,201.686005,...,53.250512,38236.38270,0.207960,1.725500e+10,0.115443,36125.36205,183788.8962,6.857685,0.117943,1.459624e+06
7,B03757,8,-912.0,-567.0,111.801578,429.421848,Infected,92028.82798,2424.278536,115.733583,...,31.518300,39117.04612,0.203260,1.422932e+10,0.107704,22780.18757,192435.5003,6.730401,0.107198,1.826858e+06
9,B03757,pre,-944.0,-720.0,58.705037,1200.810742,Infected,47030.28314,1393.810898,64.593689,...,20.641548,43584.52110,0.202894,9.508435e+09,0.139734,16558.41872,214687.6968,6.520020,0.149242,1.461371e+06

In [4]:
# Getting back the objects:
with open('../config/lists_path.pkl', 'rb') as f:
    id_cols_path,var_cols_path = pickle.load(f)

# Open cleaned data
data_path = pd.read_csv(os.path.join(PATH,'tables','data_path.csv'))
data_path = data_path.loc[data_path.StudyDay.isin(['pre','2','4','6','8'])]
data_path.head()

,Subject,StudyDay,Abolute_Neutrophil,Absolute_Basophil,Absolute_Eosinophil,Absolute_Lymphocyte,Absolute_Monocyte,Absolute_Reticulocyte,Age_d,Alanine_Aminotransferase,...,Platelet_Distribution_Width,Platelet_Large_Cell_-_Ratio,Plateletcrit,Red_Blood_Cell,Red_Cell_Distrubtion_Width_-_Coefficient,Red_Cell_Distrubtion_Width_-_Standard_De,SEX,STUDY_NO,Total_Protein,White_Blood_Cell_
2,B03757,2,3.24,0.00,0.00,1.08,0.63,25.1,1602.0,42.0,...,12.6,27.8,0.44,4.82,14.1,35.2,F,SARS-COV-2-NHP-064E-1,6.8,4.95
4,B03757,4,3.21,0.00,0.03,1.81,1.06,22.9,1604.0,47.0,...,14.0,34.9,0.50,5.32,14.3,35.6,F,SARS-COV-2-NHP-064E-1,6.4,6.11
6,B03757,6,3.96,0.01,0.04,1.69,1.11,8.3,1606.0,35.0,...,13.7,32.2,0.51,5.19,14.6,36.0,F,SARS-COV-2-NHP-064E-1,6.6,6.81
8,B03757,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,B03757,pre,6.14,0.02,0.00,2.36,0.24,61.1,1589.0,43.0,...,12.2,25.9,0.50,5.01,14.9,37.2,NaN,NaN,7.1,8.76

In [5]:
# Getting back the objects:
with open('../config/lists_imm.pkl', 'rb') as f:
    id_cols_imm,var_cols_imm = pickle.load(f)

# Open cleaned data
data_imm = pd.read_csv(os.path.join(PATH,'tables','data_imm.csv'))
data_imm = data_imm.loc[data_imm.StudyDay.isin(['pre','2','4','6','8'])]
data_imm.head()

,Subject,StudyDay,Class,G-CSF,GM-CSF,IFN-Alpha,IFN-gamma,IL-10,IL-12_23_(p40),IL-13,...,IL-6,IL-8,MCP-1,MIP-1alpha,MIP-1beta,STUDY_NO,TGF-alpha,TNF-alpha,VEGF,sCD40L
5,B03757,2,Infected,103.98,18.27,410.82,44.80,218.58,30.34,105.72,...,47.84,140.13,629.07,36.33,153.07,SARS-COV-2-NHP-064E-1,5.30,24.28,7.28,604.50
8,B03757,4,Infected,118.66,20.06,0.00,24.23,376.93,52.67,136.24,...,43.57,181.52,512.37,33.04,148.65,SARS-COV-2-NHP-064E-1,13.93,40.26,3.46,689.80
10,B03757,6,Infected,146.76,23.75,0.00,435.75,5680.62,1439.22,400.47,...,205.82,106.61,360.68,53.29,140.86,SARS-COV-2-NHP-064E-1,81.62,443.45,280.70,528.85
12,B03757,8,Infected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,B03757,pre,Infected,0.00,10.99,0.00,13.67,257.76,41.91,131.27,...,18.65,15.87,118.43,0.00,130.13,NaN,3.46,22.14,0.00,0.00

In [6]:
id_cols = id_cols_radio + id_cols_path + id_cols_imm
var_cols = var_cols_radio + var_cols_path + var_cols_imm

In [7]:
data_merge = data_path.set_index(['Subject','StudyDay']).join(data_radio.set_index(['Subject','StudyDay']),lsuffix='_path', rsuffix='_radio').reset_index()
data_merge

,Subject,StudyDay,Abolute_Neutrophil,Absolute_Basophil,Absolute_Eosinophil,Absolute_Lymphocyte,Absolute_Monocyte,Absolute_Reticulocyte,Age_d,Alanine_Aminotransferase,...,SumSquares-glcm,SurfaceArea-shape,SurfaceVolumeRatio-shape,TotalEnergy-firstorder,Uniformity-firstorder,Variance-firstorder,VoxelVolume-shape,ZoneEntropy-glszm,ZonePercentage-glszm,ZoneVariance-glszm
0,B03757,2,3.24,0.00,0.00,1.08,0.63,25.1,1602.0,42.0,...,39.705596,37015.24347,0.221905,1.503261e+10,0.096901,27707.43096,166787.9929,6.784057,0.120439,9.577950e+05
1,B03757,4,3.21,0.00,0.03,1.81,1.06,22.9,1604.0,47.0,...,54.686086,37199.49256,0.207574,1.692301e+10,0.109012,36959.53816,179172.8874,6.857994,0.117850,1.357291e+06
2,B03757,6,3.96,0.01,0.04,1.69,1.11,8.3,1606.0,35.0,...,53.250512,38236.38270,0.207960,1.725500e+10,0.115443,36125.36205,183788.8962,6.857685,0.117943,1.459624e+06
3,B03757,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.518300,39117.04612,0.203260,1.422932e+10,0.107704,22780.18757,192435.5003,6.730401,0.107198,1.826858e+06
4,B03757,pre,6.14,0.02,0.00,2.36,0.24,61.1,1589.0,43.0,...,20.641548,43584.52110,0.202894,9.508435e+09,0.139734,16558.41872,214687.6968,6.520020,0.149242,1.461371e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,H89K,2,10.63,0.01,0.41,2.66,1.20,90.7,2168.0,34.0,...,29.119061,47318.71428,0.196946,1.681323e+10,0.103148,22403.97827,240190.5968,6.791784,0.115120,2.183725e+06
116,H89K,4,8.32,0.00,0.36,2.88,1.32,75.2,2170.0,60.0,...,22.182466,50194.97086,0.194335,1.449533e+10,0.118872,17264.44997,258180.5168,6.678369,0.108457,2.310854e+06
117,H89K,6,8.58,0.00,0.43,2.47,1.18,70.4,2172.0,49.0,...,19.324347,50763.79142,0.191804,1.356920e+10,0.125325,15460.92641,264575.7545,6.609108,0.104733,3.704730e+06
118,H89K,8,10.69,0.01,0.34,2.00,1.17,73.5,2174.0,42.0,...,22.471322,50772.65700,0.194907,1.448140e+10,0.119964,17478.94997,260397.5853,6.668630,0.109983,2.685150e+06
119,H89K,pre,9.45,0.01,0.87,2.75,0.91,54.8,2159.0,19.0,...,27.752606,47704.22395,0.205519,1.577737e+10,0.099237,20794.94221,232002.5345,6.748557,0.117624,1.352953e+06

In [8]:
data_merge = data_merge.set_index(['Subject','StudyDay']).join(data_imm.set_index(['Subject','StudyDay']),rsuffix='_imm').reset_index()
data_merge

,Subject,StudyDay,Abolute_Neutrophil,Absolute_Basophil,Absolute_Eosinophil,Absolute_Lymphocyte,Absolute_Monocyte,Absolute_Reticulocyte,Age_d,Alanine_Aminotransferase,...,IL-6,IL-8,MCP-1,MIP-1alpha,MIP-1beta,STUDY_NO_imm,TGF-alpha,TNF-alpha,VEGF,sCD40L
0,B03757,2,3.24,0.00,0.00,1.08,0.63,25.1,1602.0,42.0,...,47.84,140.13,629.07,36.33,153.07,SARS-COV-2-NHP-064E-1,5.30,24.28,7.28,604.50
1,B03757,4,3.21,0.00,0.03,1.81,1.06,22.9,1604.0,47.0,...,43.57,181.52,512.37,33.04,148.65,SARS-COV-2-NHP-064E-1,13.93,40.26,3.46,689.80
2,B03757,6,3.96,0.01,0.04,1.69,1.11,8.3,1606.0,35.0,...,205.82,106.61,360.68,53.29,140.86,SARS-COV-2-NHP-064E-1,81.62,443.45,280.70,528.85
3,B03757,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B03757,pre,6.14,0.02,0.00,2.36,0.24,61.1,1589.0,43.0,...,18.65,15.87,118.43,0.00,130.13,NaN,3.46,22.14,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,H89K,2,10.63,0.01,0.41,2.66,1.20,90.7,2168.0,34.0,...,3.04,30.27,149.21,3.43,10.56,SARS-COV-2-NHP-064E-3,2.17,0.00,17.43,88.48
116,H89K,4,8.32,0.00,0.36,2.88,1.32,75.2,2170.0,60.0,...,1.77,71.00,154.44,4.58,10.74,SARS-COV-2-NHP-064E-3,2.33,14.93,0.00,140.05
117,H89K,6,8.58,0.00,0.43,2.47,1.18,70.4,2172.0,49.0,...,1.19,31.51,125.65,0.00,10.99,SARS-COV-2-NHP-064E-3,2.14,11.59,0.00,66.74
118,H89K,8,10.69,0.01,0.34,2.00,1.17,73.5,2174.0,42.0,...,NaN,NaN,NaN,NaN,NaN,SARS-COV-2-NHP-064E-3,NaN,NaN,NaN,NaN
119,H89K,pre,9.45,0.01,0.87,2.75,0.91,54.8,2159.0,19.0,...,0.00,25.46,108.54,4.58,10.08,NaN,2.27,0.00,0.00,49.58

In [9]:
def ninetynine(condition, problem):
    # condition: True if there is a problem
    if condition:
        print('I\'ve got 99 problems, and this is the 100th: ' + problem)
    else:
        print('I\'ve got 99 problems, but ' + problem + ' is not one')

In [10]:
# Check if the two datasets have matching values
ninetynine(not data_merge['Class_radio'].equals(data_merge['Class_path']),'mis-matched class labels')
ninetynine(not data_merge['Class_radio'].equals(data_merge['Class']),'mis-matched class labels')
#data_merge.loc[data_merge.Class_radio != data_merge.Class_path,['Class_path','Class_radio']]

I've got 99 problems, but mis-matched class labels is not one
I've got 99 problems, but mis-matched class labels is not one

In [11]:
# Create a single Class field
data_merge['Class_name'] = data_merge['Class_path']

# Enumerate Class
data_merge.loc[data_merge["Class_name"] == "Infected","Class"] = 1
data_merge.loc[data_merge["Class_name"] == "Mock","Class"] = 0

In [12]:
data_merge.loc[data_merge.StudyDay == '4',['Subject','Class','SEX','COUNTRY_ORIGIN']]

    Subject Class SEX COUNTRY_ORIGIN
1    B03757     1   F       Cambodia
6    B03781     1   F       Cambodia
11   B03819     1   F       Cambodia
16   B03828     0   F       Cambodia
21   B03843     0   F       Cambodia
26   B03859     0   F       Cambodia
31   B03869     0   F       Cambodia
36   B03928     0   M       Cambodia
41   B03942     0   M       Cambodia
46   B03955     1   M       Cambodia
51   B03959     1   M       Cambodia
56   B03989     1   M       Cambodia
61     G21D     0   F            nil
66     G21E     1   F            nil
71     G26Y     0   F            nil
76     G57L     0   F            nil
81     G57N     1   F            nil
86     G966     0   F            nil
91     G974     1   F            nil
96     H32F     1   M            nil
101    H38Y     1   M            nil
106    H54R     1   M            nil
111    H56N     0   M            nil
116    H89K     0   M            nil

#### Remove subjects to balance by sex and origin

In [13]:
# remove subjects to balance sex and origin
data_merge = data_merge.loc[~data_merge.Subject.isin(['B03843', 'B03869', 'G21D', 'G966'])]
print('Subjects: ',len(data_merge.Subject.unique()))

# converting pre to 0
data_merge.loc[data_merge.StudyDay == 'pre','StudyDay'] = 0

#     #Write status message, change this anytime this part of the analysis changes
#     status='SexOriginBal'
#     #status='AllSubj'
#     with open(os.path.join('analysis_status','t_merge.txt'),'w') as out_file:
#         out_file.write(status)

Subjects:  20

/sysapps/cluster/software/Anaconda3/5.3.0/envs/pythonenv/lib/python3.6/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [14]:
data_merge[['Subject','Class_name','SEX','COUNTRY_ORIGIN']].dropna().drop_duplicates().groupby(['Class_name','SEX','COUNTRY_ORIGIN']).agg('count')

                               Subject
Class_name SEX COUNTRY_ORIGIN
Infected   F   Cambodia              3
               nil                   3
           M   Cambodia              3
               nil                   3
Mock       F   Cambodia              2
               nil                   2
           M   Cambodia              2
               nil                   2

In [15]:
#data_merge[['StudyDay','Class_name','SEX','COUNTRY_ORIGIN']]#.groupby(['StudyDay','Class_name','SEX','COUNTRY_ORIGIN']).mean()

In [16]:
# var = 'IL-6'
# data_merge.loc[data_merge[var].isna(),[var,'Subject','Class','StudyDay']]

In [17]:
#data_merge.groupby(['StudyDay','Class_path']).describe()
#data_merge[var_cols + ['Subject']].groupby(['Subject']).agg('count')#.to_csv(os.path.join(PATH,'tables','data_summary.csv'))

In [18]:
for i in data_merge.columns:
    print(i)

Subject
StudyDay
Abolute_Neutrophil
Absolute_Basophil
Absolute_Eosinophil
Absolute_Lymphocyte
Absolute_Monocyte
Absolute_Reticulocyte
Age_d
Alanine_Aminotransferase
Albumin
AlbuminvGlobulin_Ratio
Aspartate_Aminotransferase
Blood_Urea_Nitrogen
C-Reactive_Protein
COUNTRY_ORIGIN
Class_path
Creatinine_
Creatinine_Kinase
Globulin
HEM
Hematocrit
Hemoglobin
ICT
LIP
Lactate_Dehydrogenase
Mean_Corpuscular_Hemoglobin
Mean_Corpuscular_Hemoglobin_Concentraion
Mean_Corpuscular_Volume
Mean_Platelet_Volume_
Percent_Basophil
Percent_Eosinophil
Percent_Lymphocyte
Percent_Monocyte
Percent_Neutrophil
Percent_Reticulocyte
Platelet
Platelet_Distribution_Width
Platelet_Large_Cell_-_Ratio
Plateletcrit
Red_Blood_Cell
Red_Cell_Distrubtion_Width_-_Coefficient
Red_Cell_Distrubtion_Width_-_Standard_De
SEX
STUDY_NO
Total_Protein
White_Blood_Cell_
10Percentile-firstorder
90Percentile-firstorder
Autocorrelation-glcm
Busyness-ngtdm
Class_radio
ClusterProminence-glcm
ClusterShade-glcm
ClusterTendency-glcm
Coarseness-ngtdm
Compactness1-shape
Compactness2-shape
Complexity-ngtdm
Contrast-glcm
Contrast-ngtdm
Correlation-glcm
DependenceEntropy-gldm
DependenceNonUniformity-gldm
DependenceNonUniformityNormalized-gldm
DependenceVariance-gldm
DifferenceAverage-glcm
DifferenceEntropy-glcm
DifferenceVariance-glcm
Elongation-shape
Energy-firstorder
Entropy-firstorder
File Name
Flatness-shape
GrayLevelNonUniformity-gldm
GrayLevelNonUniformity-glrlm
GrayLevelNonUniformity-glszm
GrayLevelNonUniformityNormalized-glrlm
GrayLevelNonUniformityNormalized-glszm
GrayLevelVariance-gldm
GrayLevelVariance-glrlm
GrayLevelVariance-glszm
HighGrayLevelEmphasis-gldm
HighGrayLevelRunEmphasis-glrlm
HighGrayLevelZoneEmphasis-glszm
Id-glcm
Idm-glcm
Idmn-glcm
Idn-glcm
Imc1-glcm
Imc2-glcm
InterquartileRange-firstorder
InverseVariance-glcm
JointAverage-glcm
JointEnergy-glcm
JointEntropy-glcm
Kurtosis-firstorder
LargeAreaEmphasis-glszm
LargeAreaHighGrayLevelEmphasis-glszm
LargeAreaLowGrayLevelEmphasis-glszm
LargeDependenceEmphasis-gldm
LargeDependenceHighGrayLevelEmphasis-gldm
LargeDependenceLowGrayLevelEmphasis-gldm
LeastAxisLength-shape
LongRunEmphasis-glrlm
LongRunHighGrayLevelEmphasis-glrlm
LongRunLowGrayLevelEmphasis-glrlm
LowGrayLevelEmphasis-gldm
LowGrayLevelRunEmphasis-glrlm
LowGrayLevelZoneEmphasis-glszm
MCC-glcm
MajorAxisLength-shape
Maximum-firstorder
Maximum2DDiameterColumn-shape
Maximum2DDiameterRow-shape
Maximum2DDiameterSlice-shape
Maximum3DDiameter-shape
MaximumProbability-glcm
Mean-firstorder
MeanAbsoluteDeviation-firstorder
Median-firstorder
MeshVolume-shape
Minimum-firstorder
MinorAxisLength-shape
Range-firstorder
RobustMeanAbsoluteDeviation-firstorder
RootMeanSquared-firstorder
RunEntropy-glrlm
RunLengthNonUniformity-glrlm
RunLengthNonUniformityNormalized-glrlm
RunPercentage-glrlm
RunVariance-glrlm
ShortRunEmphasis-glrlm
ShortRunHighGrayLevelEmphasis-glrlm
ShortRunLowGrayLevelEmphasis-glrlm
SizeZoneNonUniformity-glszm
SizeZoneNonUniformityNormalized-glszm
Skewness-firstorder
SmallAreaEmphasis-glszm
SmallAreaHighGrayLevelEmphasis-glszm
SmallAreaLowGrayLevelEmphasis-glszm
SmallDependenceEmphasis-gldm
SmallDependenceHighGrayLevelEmphasis-gldm
SmallDependenceLowGrayLevelEmphasis-gldm
SphericalDisproportion-shape
Sphericity-shape
StandardDeviation-firstorder
Strength-ngtdm
Study
StudyDate
SumAverage-glcm
SumEntropy-glcm
SumSquares-glcm
SurfaceArea-shape
SurfaceVolumeRatio-shape
TotalEnergy-firstorder
Uniformity-firstorder
Variance-firstorder
VoxelVolume-shape
ZoneEntropy-glszm
ZonePercentage-glszm
ZoneVariance-glszm
Class
G-CSF
GM-CSF
IFN-Alpha
IFN-gamma
IL-10
IL-12_23_(p40)
IL-13
IL-15
IL-17a
IL-18
IL-1b
IL-1ra
IL-2
IL-4
IL-5
IL-6
IL-8
MCP-1
MIP-1alpha
MIP-1beta
STUDY_NO_imm
TGF-alpha
TNF-alpha
VEGF
sCD40L
Class_name

In [19]:
#data_merge.reset_index().groupby('StudyDay','Class_path').describe()
data_merge['StudyDay'].unique()

array(['2', '4', '6', '8', 0], dtype=object)

In [20]:
data_merge.set_index(['Subject','StudyDay']).to_csv(os.path.join(PATH,'tables','data_merge_noDelta.csv'))

In [21]:
data_merge_246 = data_merge.loc[data_merge.StudyDay != '8']
data_merge_246.set_index(['Subject','StudyDay']).to_csv(os.path.join(PATH,'tables','data_merge246_noDelta.csv'))

In [22]:
#Check for any NA values in the 246 table, cannot have NA values for future analyses
for var in var_cols:
    if data_merge_246[var].isna().any():
        print(data_merge_246.loc[data_merge_246[var].isna(),[var,'Subject','StudyDay']])

In [23]:
id_cols

['Study',
 'Subject',
 'StudyDay',
 'StudyDate',
 'File Name',
 'STUDY_NO',
 'Class',
 'Subject',
 'SEX',
 'COUNTRY_ORIGIN',
 'StudyDay',
 'Age_d',
 'STUDY_NO',
 'Class',
 'Subject',
 'StudyDay']

In [24]:
#var_cols.remove('C-Reactive_Protein')
#var_cols.remove('Creatinine_Kinase')
#data = data.loc[data.StudyDay != '8_delta'].reset_index()